# Generated by Django 5.0.2 on 2024-04-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_line',
            name='unit',
            field=models.CharField(blank=True, choices=[('t', 'tsp'), ('T', 'Tbsp'), ('c', 'cups'), ('o', 'ounces')], max_length=1, null=True),
        ),
    ]
