# Generated by Django 5.0.2 on 2024-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_line_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_line',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'None'), ('t', 'tsp'), ('T', 'Tbsp'), ('c', 'cups'), ('o', 'ounces')], max_length=1, null=True),
        ),
    ]
